In [1]:
#import requuired libraries
import pandas as pd
import numpy as np
import sys
import joblib
sys.modules['sklearn.externals.joblib'] = joblib
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV , train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, roc_auc_score, recall_score

import pickle
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('Group_9_data_cleaned.csv')
df

Unnamed: 0  current_1     current_2     current_3  current_4  \
0               1        0.0 -3.014600e-07  8.260300e-06  -0.000012   
1               2        1.0  2.913200e-06 -5.247700e-06   0.000003   
2               3        2.0 -2.951700e-06 -3.184000e-06  -0.000016   
3               4        3.0 -1.322600e-06  8.820100e-06  -0.000016   
4               5        4.0 -6.836600e-08  5.666300e-07  -0.000026   
...           ...        ...           ...           ...        ...   
58504       58505    58504.0 -9.982500e-06  1.854900e-06  -0.000021   
58505       58506    58505.0 -1.055400e-05  1.983500e-05   0.000031   
58506       58507    58506.0 -5.857700e-06  1.859400e-05  -0.000102   
58507       58508    58507.0 -4.441100e-06  3.396900e-05  -0.000294   
58508       58509    58508.0 -8.853300e-06  5.225900e-05   0.000072   

       current_5     current_6  current_7  current_8  current_9  ...  \
0      -0.000002 -1.438600e-06  -0.000021   0.031718   0.031710  ...   
1      -0.000006  2.778900e-06  -0.000004   0.030804   0.030810  ...   
2      -0.000001 -1.575300e-06   0.000017   0.032877   0.032880  ...   
3      -0.000005 -7.282900e-07   0.000004   0.029410   0.029401  ...   
4      -0.000006 -7.940600e-07   0.000013   0.030119   0.030119  ...   
...          ...           ...        ...        ...        ...  ...   
58504   0.000017 -5.910200e-06  -0.000098  -0.083417  -0.083419  ...   
58505  -0.000018 -6.547550e-05   0.000289  -0.085131  -0.085151  ...   
58506  -0.000003  3.827500e-06   0.000117  -0.081989  -0.082008  ...   
58507   0.000005  6.500800e-06   0.000087  -0.081500  -0.081534  ...   
58508   0.000010  3.795600e-06  -0.000032  -0.083034  -0.083086  ...   

       current_41  current_42  current_43  current_44  current_45  current_46  \
0        -0.63308      2.9646      8.1198     -1.4961     -1.4961     -1.4961   
1        -0.59314      7.6252      6.1690     -1.4967     -1.4967     -1.4967   
2        -0.63252      2.7784      5.3017     -1.4983     -1.4983     -1.4982   
3        -0.62289      6.5534      6.2606     -1.4963     -1.4963     -1.4963   
4        -0.63010      4.5155      9.5231     -1.4958     -1.4958     -1.4958   
...           ...         ...         ...         ...         ...         ...   
58504    -0.52907      1.4641      7.0032     -1.5024     -1.5025     -1.5023   
58505    -0.51971      3.3275      2.3072     -1.5024     -1.5025     -1.5024   
58506    -0.51103     18.5458      9.0437     -1.5035     -1.5035     -1.5039   
58507    -0.52033      1.3890     10.7430     -1.5029     -1.5029     -1.5030   
58508    -0.50974      1.6026      4.5773     -1.5039     -1.5040     -1.5036   

       current_47  current_48  current_49  output  
0         -1.4996    -1.49960    -1.49960       1  
1         -1.5005    -1.50050    -1.50050       1  
2         -1.4985    -1.49850    -1.49850       1  
3         -1.4975    -1.49750    -1.49760       1  
4         -1.4959    -1.49590    -1.49590       1  
...           ...         ...         ...     ...  
58504     -1.4933    -1.49330    -1.49330      11  
58505     -1.4925    -1.49250    -1.49260      11  
58506     -1.4911    -1.49135    -1.49125      11  
58507     -1.4932    -1.49320    -1.49310      11  
58508     -1.4945    -1.49460    -1.49430      11  

[58509 rows x 51 columns]

In [3]:
df = df.iloc[:,1:]
df

current_1     current_2     current_3  current_4  current_5  \
0            0.0 -3.014600e-07  8.260300e-06  -0.000012  -0.000002   
1            1.0  2.913200e-06 -5.247700e-06   0.000003  -0.000006   
2            2.0 -2.951700e-06 -3.184000e-06  -0.000016  -0.000001   
3            3.0 -1.322600e-06  8.820100e-06  -0.000016  -0.000005   
4            4.0 -6.836600e-08  5.666300e-07  -0.000026  -0.000006   
...          ...           ...           ...        ...        ...   
58504    58504.0 -9.982500e-06  1.854900e-06  -0.000021   0.000017   
58505    58505.0 -1.055400e-05  1.983500e-05   0.000031  -0.000018   
58506    58506.0 -5.857700e-06  1.859400e-05  -0.000102  -0.000003   
58507    58507.0 -4.441100e-06  3.396900e-05  -0.000294   0.000005   
58508    58508.0 -8.853300e-06  5.225900e-05   0.000072   0.000010   

          current_6  current_7  current_8  current_9  current_10  ...  \
0     -1.438600e-06  -0.000021   0.031718   0.031710    0.031721  ...   
1      2.778900e-06  -0.000004   0.030804   0.030810    0.030806  ...   
2     -1.575300e-06   0.000017   0.032877   0.032880    0.032896  ...   
3     -7.282900e-07   0.000004   0.029410   0.029401    0.029417  ...   
4     -7.940600e-07   0.000013   0.030119   0.030119    0.030145  ...   
...             ...        ...        ...        ...         ...  ...   
58504 -5.910200e-06  -0.000098  -0.083417  -0.083419   -0.083398  ...   
58505 -6.547550e-05   0.000289  -0.085131  -0.085151   -0.085182  ...   
58506  3.827500e-06   0.000117  -0.081989  -0.082008   -0.081906  ...   
58507  6.500800e-06   0.000087  -0.081500  -0.081534   -0.081093  ...   
58508  3.795600e-06  -0.000032  -0.083034  -0.083086   -0.083159  ...   

       current_41  current_42  current_43  current_44  current_45  current_46  \
0        -0.63308      2.9646      8.1198     -1.4961     -1.4961     -1.4961   
1        -0.59314      7.6252      6.1690     -1.4967     -1.4967     -1.4967   
2        -0.63252      2.7784      5.3017     -1.4983     -1.4983     -1.4982   
3        -0.62289      6.5534      6.2606     -1.4963     -1.4963     -1.4963   
4        -0.63010      4.5155      9.5231     -1.4958     -1.4958     -1.4958   
...           ...         ...         ...         ...         ...         ...   
58504    -0.52907      1.4641      7.0032     -1.5024     -1.5025     -1.5023   
58505    -0.51971      3.3275      2.3072     -1.5024     -1.5025     -1.5024   
58506    -0.51103     18.5458      9.0437     -1.5035     -1.5035     -1.5039   
58507    -0.52033      1.3890     10.7430     -1.5029     -1.5029     -1.5030   
58508    -0.50974      1.6026      4.5773     -1.5039     -1.5040     -1.5036   

       current_47  current_48  current_49  output  
0         -1.4996    -1.49960    -1.49960       1  
1         -1.5005    -1.50050    -1.50050       1  
2         -1.4985    -1.49850    -1.49850       1  
3         -1.4975    -1.49750    -1.49760       1  
4         -1.4959    -1.49590    -1.49590       1  
...           ...         ...         ...     ...  
58504     -1.4933    -1.49330    -1.49330      11  
58505     -1.4925    -1.49250    -1.49260      11  
58506     -1.4911    -1.49135    -1.49125      11  
58507     -1.4932    -1.49320    -1.49310      11  
58508     -1.4945    -1.49460    -1.49430      11  

[58509 rows x 50 columns]

In [4]:
X = df.drop(['output'],axis=1)
y = df['output']

In [5]:
X_train, X_test, y_train, y_test  = train_test_split(X, y, train_size = 0.5, random_state = 42)

# Random Forest

In [6]:
randf = RandomForestClassifier()

In [7]:
sfs = SFS(randf,
         k_features=(1,49),forward=True,
                                floating=True,
                                scoring='accuracy')

In [8]:
sfs.fit(X_train,y_train)

SequentialFeatureSelector(estimator=RandomForestClassifier(), floating=True,
                          k_features=(1, 49), scoring='accuracy')

In [9]:
sfs.k_feature_names_

('current_1', 'current_16', 'current_20', 'current_42')

In [10]:
x_train_feat = X_train[list(sfs.k_feature_names_)]
x_test_feat=X_test[list(sfs.k_feature_names_)]

In [11]:
# Define a grid of hyperparameters to search over
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
}

In [12]:
# Create a Grid Search CV object and fit it to the Validation data
grid_search = GridSearchCV(randf, param_grid, cv=5)
grid_search.fit(x_train_feat, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [5, 10], 'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100]})

In [13]:
grid_search.best_params_

{'max_depth': 10,
 'min_samples_leaf': 2,
 'min_samples_split': 2,
 'n_estimators': 100}

In [14]:
# best classification tree for the above data
best_rf = RandomForestClassifier(max_depth = 10, min_samples_leaf= 1, min_samples_split= 2, n_estimators= 50)
best_rf.fit(x_train_feat,y_train)
filename = 'RF_class.sav'
pickle.dump(best_rf, open(filename, 'wb'))

In [15]:
# Best model training 
best_rf.fit(x_train_feat,y_train)
# Accuracy scores of best tree on different datasets
y_train_pred = best_rf.predict(x_train_feat)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
y_test_pred = best_rf.predict(x_test_feat)
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}") 

 The training data accuracy for the best model is 1.0
 The testing data accuracy for the best model is 1.0


In [16]:
### Training Data
print(confusion_matrix(y_train,y_train_pred))

[[2643    0    0    0    0    0    0    0    0    0    0]
 [   0 2623    0    0    0    0    0    0    0    0    0]
 [   0    0 2685    0    0    0    0    0    0    0    0]
 [   0    0    0 2679    0    0    0    0    0    0    0]
 [   0    0    0    0 2716    0    0    0    0    0    0]
 [   0    0    0    0    0 2626    0    0    0    0    0]
 [   0    0    0    0    0    0 2609    0    0    0    0]
 [   0    0    0    0    0    0    0 2665    0    0    0]
 [   0    0    0    0    0    0    0    0 2693    0    0]
 [   0    0    0    0    0    0    0    0    0 2663    0]
 [   0    0    0    0    0    0    0    0    0    0 2652]]


In [17]:
# Confusion matrix for testing data
print(confusion_matrix(y_test,y_test_pred))

[[2676    0    0    0    0    0    0    0    0    0    0]
 [   0 2696    0    0    0    0    0    0    0    0    0]
 [   0    0 2634    0    0    0    0    0    0    0    0]
 [   0    0    0 2640    0    0    0    0    0    0    0]
 [   0    0    0    0 2603    0    0    0    0    0    0]
 [   0    0    0    0    0 2693    0    0    0    0    0]
 [   0    0    0    0    0    0 2710    0    0    0    0]
 [   0    0    0    0    0    0    0 2654    0    0    0]
 [   0    0    0    0    0    0    0    0 2626    0    0]
 [   0    0    0    0    0    0    0    0    0 2656    0]
 [   0    0    0    0    0    0    0    0    0    0 2667]]


In [18]:
#Classification report for the training data
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      2643
           2       1.00      1.00      1.00      2623
           3       1.00      1.00      1.00      2685
           4       1.00      1.00      1.00      2679
           5       1.00      1.00      1.00      2716
           6       1.00      1.00      1.00      2626
           7       1.00      1.00      1.00      2609
           8       1.00      1.00      1.00      2665
           9       1.00      1.00      1.00      2693
          10       1.00      1.00      1.00      2663
          11       1.00      1.00      1.00      2652

    accuracy                           1.00     29254
   macro avg       1.00      1.00      1.00     29254
weighted avg       1.00      1.00      1.00     29254



In [19]:
# Classification report for the testing data
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      2676
           2       1.00      1.00      1.00      2696
           3       1.00      1.00      1.00      2634
           4       1.00      1.00      1.00      2640
           5       1.00      1.00      1.00      2603
           6       1.00      1.00      1.00      2693
           7       1.00      1.00      1.00      2710
           8       1.00      1.00      1.00      2654
           9       1.00      1.00      1.00      2626
          10       1.00      1.00      1.00      2656
          11       1.00      1.00      1.00      2667

    accuracy                           1.00     29255
   macro avg       1.00      1.00      1.00     29255
weighted avg       1.00      1.00      1.00     29255



In [20]:
# roc auc score for training data
y_train_prob = best_rf.predict_proba(x_train_feat)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the testing data
y_test_prob = best_rf.predict_proba(x_test_feat)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 1.0
 The roc_auc score for the testing data is 1.0


In [21]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test,y_test_pred,average= 'macro')}")

 The recall score for the training data is 1.0
 The recall score for the testing data is 1.0


# Using Deep Learning


In [6]:
# Importing the deep learning model
from sklearn.neural_network import MLPClassifier

In [7]:
from sklearn.preprocessing import MinMaxScaler
X_train_scaled=df
scaler = MinMaxScaler()
X_train_scaled.iloc[:,0:49] = scaler.fit_transform(X_train_scaled.iloc[:,0:49])
X_train_scaled=X_train_scaled.drop(['output'],axis=1)
X_train_scaled

current_1  current_2  current_3  current_4  current_5  current_6  \
0       0.000000   0.573003   0.545858   0.478118   0.461592   0.473436   
1       0.000017   0.662282   0.444205   0.503286   0.357206   0.504616   
2       0.000034   0.499399   0.459736   0.470660   0.492282   0.472425   
3       0.000051   0.544643   0.550071   0.470729   0.391897   0.478687   
4       0.000068   0.579476   0.487960   0.453745   0.345113   0.478201   
...          ...        ...        ...        ...        ...        ...   
58504   0.999932   0.304136   0.497655   0.461972   1.000000   0.440376   
58505   0.999949   0.288264   0.632962   0.550648   0.023902   0.000000   
58506   0.999966   0.418692   0.623623   0.325348   0.429034   0.512369   
58507   0.999983   0.458034   0.739325   0.000000   0.669813   0.532133   
58508   1.000000   0.335496   0.876964   0.620369   0.803657   0.512133   

       current_7  current_8  current_9  current_10  ...  current_40  \
0       0.465521   0.760361   0.760392    0.760360  ...    0.310740   
1       0.495609   0.754506   0.754629    0.754498  ...    0.174333   
2       0.532024   0.767786   0.767883    0.767887  ...    0.298519   
3       0.509207   0.745576   0.745607    0.745601  ...    1.000000   
4       0.525303   0.750118   0.750204    0.750264  ...    0.256528   
...          ...        ...        ...         ...  ...         ...   
58504   0.333676   0.022777   0.023196    0.022933  ...    0.388620   
58505   1.000000   0.011797   0.012105    0.011505  ...    0.188483   
58506   0.704289   0.031926   0.032231    0.032490  ...    0.688359   
58507   0.652458   0.035058   0.035266    0.037698  ...    0.218875   
58508   0.446735   0.025231   0.025328    0.024464  ...    0.290064   

       current_41  current_42  current_43  current_44  current_45  current_46  \
0        0.498090    0.186047    0.441411    0.727941    0.725962       0.730   
1        0.571970    0.429514    0.331001    0.698529    0.697115       0.700   
2        0.499126    0.176320    0.281914    0.620098    0.620192       0.625   
3        0.516939    0.373524    0.336185    0.718137    0.716346       0.720   
4        0.503602    0.267065    0.520835    0.742647    0.740385       0.745   
...           ...         ...         ...         ...         ...         ...   
58504    0.690486    0.107662    0.378215    0.419118    0.418269       0.420   
58505    0.707800    0.205005    0.112433    0.419118    0.418269       0.415   
58506    0.723856    1.000000    0.493702    0.365196    0.370192       0.340   
58507    0.706653    0.103739    0.589878    0.394608    0.399038       0.385   
58508    0.726242    0.114897    0.240915    0.345588    0.346154       0.355   

       current_47  current_48  current_49  
0        0.375000    0.375000    0.367424  
1        0.308824    0.306818    0.299242  
2        0.455882    0.458333    0.450758  
3        0.529412    0.534091    0.518939  
4        0.647059    0.655303    0.647727  
...           ...         ...         ...  
58504    0.838235    0.852273    0.844697  
58505    0.897059    0.912879    0.897727  
58506    1.000000    1.000000    1.000000  
58507    0.845588    0.859848    0.859848  
58508    0.750000    0.753788    0.768939  

[58509 rows x 49 columns]

In [8]:
X_train_scaled, X_test_scaled, y_train_scaled, y_test_scaled  = train_test_split(X_train_scaled, y, train_size = 0.5, random_state = 42)

In [9]:
from sklearn.model_selection import RandomizedSearchCV
mlp = MLPClassifier()

In [10]:
sfs_deep = SFS(mlp,
         k_features=(1,49),forward=True,
                                floating=True,
                                scoring='accuracy')

In [ ]:
sfs_deep.fit(X_train_scaled,y_train_scaled)

In [ ]:
#best fetures
sfs_deep.k_feature_names_

In [ ]:
x_train_deep_feat = X_train_scaled[list(sfs_deep.k_feature_names_)]
x_test_deep_feat=X_test_scaled[list(sfs_deep.k_feature_names_)]

In [ ]:
# Define the parameter grid
param_grid = {
    'hidden_layer_sizes': [(100,), (200,), (500,), (1000,)],
    'activation': ['relu', 'logistic'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'adaptive'],
}

In [ ]:
# Perform grid search cross-validation
clf = RandomizedSearchCV(mlp, param_grid, random_state=0)

In [ ]:
clf.fit(x_train_deep_feat, y_train_scaled)

In [ ]:
# Print the best hyperparameters
print(f'Best hyperparameters: {clf.best_params_}')

In [ ]:
# best model 
best_model_mlp =  MLPClassifier(solver= 'adam', learning_rate= 'adaptive', hidden_layer_sizes= (500,), alpha= 0.001, activation= 'relu')
best_model_mlp.fit(x_train_deep_feat,y_train_scaled)

In [ ]:
filename = 'mlp_class.sav'
pickle.dump(best_model_mlp, open(filename, 'wb'))

In [ ]:
y_train_pred_deep_feat = best_model_mlp.predict(x_train_deep_feat)
y_test_pred_deep_feat  = best_model_mlp.predict(x_test_deep_feat)
print(f" The training data accuracy for the best model is {accuracy_score(y_train_scaled,y_train_pred_deep_feat)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test_scaled,y_test_pred_deep_feat)}")

In [ ]:
### Training Data
print(confusion_matrix(y_train_scaled,y_train_pred_deep_feat))

In [ ]:
### Testing Data
print(confusion_matrix(y_test_scaled,y_test_pred_deep_feat))

In [ ]:
#Classification report for the training data
print(classification_report(y_train_scaled,y_train_pred_deep_feat))

In [ ]:
#Classification report for the testing data
print(classification_report(y_test_scaled,y_test_pred_deep_feat))

In [ ]:
# roc auc score for training data
y_train_prob = best_model_mlp.predict_proba(x_train_deep_feat)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train_scaled,y_train_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the testing data
y_test_prob = best_model_mlp.predict_proba(x_test_deep_feat)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test_scaled,y_test_prob,average='weighted',multi_class='ovr')}")

In [ ]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train_scaled,y_train_pred_deep_feat,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test_scaled,y_test_pred_deep_feat,average= 'macro')}")

In [ ]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train_scaled,y_train_pred_deep_feat,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_test_scaled,y_test_pred_deep_feat,average= 'weighted')}")