In [62]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pickle
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, roc_auc_score, recall_score
from sklearn.model_selection import GridSearchCV, train_test_split

In [63]:
data = pd.read_csv('Group_9_data_cleaned.csv')
data.head(3)
# removing a redundant column
df = data.drop(['Unnamed: 0'],axis=1)
df.head()

current_1     current_2  current_3  current_4     current_5  current_6  \
0 -3.014600e-07  8.260300e-06  -0.000012  -0.000002 -1.438600e-06  -0.000021   
1  2.913200e-06 -5.247700e-06   0.000003  -0.000006  2.778900e-06  -0.000004   
2 -2.951700e-06 -3.184000e-06  -0.000016  -0.000001 -1.575300e-06   0.000017   
3 -1.322600e-06  8.820100e-06  -0.000016  -0.000005 -7.282900e-07   0.000004   
4 -6.836600e-08  5.666300e-07  -0.000026  -0.000006 -7.940600e-07   0.000013   

   current_7  current_8  current_9  current_10  ...  current_40  current_41  \
0   0.031718   0.031710   0.031721   -0.032963  ...    -0.63308      2.9646   
1   0.030804   0.030810   0.030806   -0.033520  ...    -0.59314      7.6252   
2   0.032877   0.032880   0.032896   -0.029834  ...    -0.63252      2.7784   
3   0.029410   0.029401   0.029417   -0.030156  ...    -0.62289      6.5534   
4   0.030119   0.030119   0.030145   -0.031393  ...    -0.63010      4.5155   

   current_42  current_43  current_44  current_45  current_46  current_47  \
0      8.1198     -1.4961     -1.4961     -1.4961     -1.4996     -1.4996   
1      6.1690     -1.4967     -1.4967     -1.4967     -1.5005     -1.5005   
2      5.3017     -1.4983     -1.4983     -1.4982     -1.4985     -1.4985   
3      6.2606     -1.4963     -1.4963     -1.4963     -1.4975     -1.4975   
4      9.5231     -1.4958     -1.4958     -1.4958     -1.4959     -1.4959   

   current_48  output  
0     -1.4996       1  
1     -1.5005       1  
2     -1.4985       1  
3     -1.4976       1  
4     -1.4959       1  

[5 rows x 49 columns]

In [64]:
#shape of the data 
# The data has 58509 rows 
# The data has 49 features 
df.shape

(58509, 49)

In [65]:
# statistics of the data 
df.describe()

current_1     current_2     current_3     current_4     current_5  \
count  58509.000000  5.850900e+04  5.850900e+04  5.850900e+04  5.850900e+04   
mean      -0.000003  1.756436e-06  1.111802e-06 -9.722586e-07  1.775487e-06   
std        0.000008  3.199783e-05  1.520782e-04  7.956279e-06  3.234750e-05   
min       -0.000021 -6.427550e-05 -2.937900e-04 -1.887580e-05 -6.547550e-05   
25%       -0.000007 -1.444400e-05 -7.239600e-05 -5.417500e-06 -1.475300e-05   
50%       -0.000003  8.804600e-07  5.137700e-07 -1.059100e-06  7.540200e-07   
75%        0.000002  1.877700e-05  7.520000e-05  3.554700e-06  1.906200e-05   
max        0.000015  6.860850e-05  2.965940e-04  1.701300e-05  6.978450e-05   

          current_6     current_7     current_8     current_9    current_10  \
count  5.850900e+04  58509.000000  58509.000000  58509.000000  58509.000000   
mean  -7.457535e-07      0.002854      0.002849      0.002849     -0.006349   
std    1.490893e-04      0.033692      0.033700      0.033701      0.050735   
min   -2.915565e-04     -0.086972     -0.087041     -0.086978     -0.111281   
25%   -7.379100e-05     -0.019927     -0.019951     -0.019925     -0.032144   
50%   -1.659300e-07      0.013226      0.013230      0.013247     -0.015566   
75%    7.138600e-05      0.024770      0.024776      0.024777      0.020614   
max    2.891515e-04      0.069125      0.069130      0.069131      0.099751   

       ...    current_40    current_41    current_42    current_43  \
count  ...  58509.000000  58509.000000  58509.000000  58509.000000   
mean   ...     -0.650427      5.730645      7.702923     -1.500891   
std    ...      0.100670      5.781169      4.347205      0.003629   
min    ...     -0.902350     -0.596830      0.320660     -1.510950   
25%    ...     -0.715470      1.450300      4.436300     -1.503300   
50%    ...     -0.661710      3.301300      6.479100     -1.500300   
75%    ...     -0.573980      8.288500      9.857500     -1.498200   
max    ...     -0.361745     18.545800     17.989300     -1.490550   

         current_44    current_45    current_46    current_47    current_48  \
count  58509.000000  58509.000000  58509.000000  58509.000000  58509.000000   
mean      -1.500915     -1.500809     -1.497787     -1.497814     -1.497710   
std        0.003640      0.003600      0.003002      0.002984      0.002988   
min       -1.511200     -1.510700     -1.504700     -1.504550     -1.504450   
25%       -1.503400     -1.503200     -1.499600     -1.499600     -1.499500   
50%       -1.500300     -1.500300     -1.498100     -1.498100     -1.498000   
75%       -1.498200     -1.498200     -1.496200     -1.496300     -1.496200   
max       -1.490400     -1.490700     -1.491100     -1.491350     -1.491250   

             output  
count  58509.000000  
mean       6.000000  
std        3.162305  
min        1.000000  
25%        3.000000  
50%        6.000000  
75%        9.000000  
max       11.000000  

[8 rows x 49 columns]

In [66]:
# There are 11 different classes in the output data 
# which are from 1 to 11 classes 
df['output'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int64)

In [67]:
# Checking for the number of each output class labels 
# It is a blanced multi class dataset with each class is having equal number of output labels 
df['output'].value_counts()

1     5319
2     5319
3     5319
4     5319
5     5319
6     5319
7     5319
8     5319
9     5319
10    5319
11    5319
Name: output, dtype: int64

# first variable selection using lasso 

In [68]:
from sklearn.linear_model import Lasso
from sklearn.preprocessing import StandardScaler

# Load data
# Dividing input and output labels
X = df.drop(['output'],axis=1)
y = df['output']


# Scale data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Create Lasso object
lasso = Lasso(alpha=0.1)

# Fit Lasso
lasso.fit(X_scaled, y)

# Get coefficients
coefficients = lasso.coef_

# Print selected features
selected_features = []
for feature, coef in zip(X.columns, coefficients):
    if coef != 0:
        print(feature)
        selected_features.append(feature)
   

current_2
current_4
current_5
current_7
current_8
current_10
current_12
current_19
current_20
current_21
current_25
current_28
current_33
current_34
current_35
current_37
current_44


In [69]:
print(selected_features)

['current_2', 'current_4', 'current_5', 'current_7', 'current_8', 'current_10', 'current_12', 'current_19', 'current_20', 'current_21', 'current_25', 'current_28', 'current_33', 'current_34', 'current_35', 'current_37', 'current_44']


In [70]:
X = df[selected_features] 
y = df['output']

X

current_2  current_4     current_5  current_7  current_8  \
0      8.260300e-06  -0.000002 -1.438600e-06   0.031718   0.031710   
1     -5.247700e-06  -0.000006  2.778900e-06   0.030804   0.030810   
2     -3.184000e-06  -0.000001 -1.575300e-06   0.032877   0.032880   
3      8.820100e-06  -0.000005 -7.282900e-07   0.029410   0.029401   
4      5.666300e-07  -0.000006 -7.940600e-07   0.030119   0.030119   
...             ...        ...           ...        ...        ...   
58504  1.854900e-06   0.000017 -5.910200e-06  -0.083417  -0.083419   
58505  1.983500e-05  -0.000018 -6.547550e-05  -0.085131  -0.085151   
58506  1.859400e-05  -0.000003  3.827500e-06  -0.081989  -0.082008   
58507  3.396900e-05   0.000005  6.500800e-06  -0.081500  -0.081534   
58508  5.225900e-05   0.000010  3.795600e-06  -0.083034  -0.083086   

       current_10  current_12  current_19  current_20  current_21  current_25  \
0       -0.032963   -0.032941     0.89669     0.89669     0.89669    0.007680   
1       -0.033520   -0.033519     0.89583     0.89583     0.89580   -0.009402   
2       -0.029834   -0.029849     0.89583     0.89583     0.89581    0.005951   
3       -0.030156   -0.030159     0.89480     0.89481     0.89479    0.002056   
4       -0.031393   -0.031405     0.89656     0.89656     0.89655   -0.000860   
...           ...         ...         ...         ...         ...         ...   
58504   -0.111281   -0.111323     2.29100     2.29090     2.29060    0.023419   
58505   -0.111281   -0.111323     2.29210     2.29200     2.29110    0.015612   
58506   -0.111281   -0.111323     2.29070     2.29070     2.28960    0.007406   
58507   -0.111281   -0.111323     2.29050     2.29040     2.28980    0.019670   
58508   -0.111281   -0.111323     2.29300     2.29290     2.29220    0.029245   

       current_28  current_33  current_34  current_35  current_37  current_44  
0        0.004879   -0.001248   -0.004378   -0.004384    -0.66732     -1.4961  
1        0.007111    0.001068   -0.001344   -0.001342    -0.65404     -1.4967  
2        0.000445    0.002885    0.000350    0.000358    -0.67146     -1.4983  
3        0.006936   -0.001277   -0.004974   -0.004966    -0.67766     -1.4963  
4        0.005616   -0.003800   -0.004655   -0.004646    -0.65867     -1.4958  
...           ...         ...         ...         ...         ...         ...  
58504    0.004317   -0.008362    0.001726    0.001733    -0.41812     -1.5025  
58505    0.007677   -0.009709   -0.000064    0.000033    -0.42137     -1.5025  
58506    0.008709   -0.008109    0.000646    0.000523    -0.39929     -1.5035  
58507    0.003671   -0.010470   -0.000125   -0.000153    -0.43276     -1.5029  
58508   -0.010920   -0.010627   -0.001158   -0.001167    -0.43513     -1.5040  

[58509 rows x 17 columns]

In [71]:
y

0         1
1         1
2         1
3         1
4         1
         ..
58504    11
58505    11
58506    11
58507    11
58508    11
Name: output, Length: 58509, dtype: int64

### Now using the best model from Part 2 with the above selected variables. Here, we got Random Forests as the best model.

In [72]:
# dividing the dataset into train,test and validation sets
X_train, X_rem, y_train, y_rem  = train_test_split(X, y, train_size = 0.5, random_state = 42)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size = 0.5, random_state = 42)


X_train

current_2     current_4     current_5  current_7  current_8  \
11040  4.852900e-06 -4.779300e-06  2.542500e-06   0.003926   0.003921   
11289 -8.251500e-06 -8.923300e-07 -4.367600e-06   0.012692   0.012701   
35768  3.467800e-05  4.093600e-07  5.364300e-06   0.036610   0.036575   
3      8.820100e-06 -4.811100e-06 -7.282900e-07   0.029410   0.029401   
5599  -9.204200e-07 -7.352800e-06  3.407100e-06  -0.028637  -0.028636   
...             ...           ...           ...        ...        ...   
54343 -5.532400e-06 -3.484000e-08 -3.860900e-06  -0.071745  -0.071739   
38158  1.568000e-06  6.281500e-07  1.255600e-06   0.042352   0.042350   
860    6.599000e-06 -9.159900e-07 -1.304700e-06   0.025901   0.025895   
15795 -6.427550e-05  5.818100e-06  3.163500e-05  -0.003429  -0.003350   
56422 -2.880500e-05 -1.887580e-05 -5.429700e-05  -0.086972  -0.087041   

       current_10  current_12  current_19  current_20  current_21  current_25  \
11040    0.001160    0.001170      1.2888     1.28880     1.28880    0.001646   
11289    0.021589    0.021610      1.7031     1.70310     1.70310   -0.003381   
35768    0.099751    0.099757      1.7128     1.71270     1.71200   -0.015251   
3       -0.030156   -0.030159      0.8948     0.89481     0.89479    0.002056   
5599    -0.036603   -0.036589      1.0765     1.07650     1.07640    0.009385   
...           ...         ...         ...         ...         ...         ...   
54343   -0.111281   -0.111323      1.2198     1.21980     1.21950    0.012522   
38158    0.023688    0.023703      1.8583     1.85830     1.85830   -0.003804   
860     -0.040507   -0.040514      1.3382     1.33820     1.33820    0.012896   
15795    0.020371    0.019904      2.1107     2.11060     2.10960   -0.028799   
56422   -0.111281   -0.111323      1.3753     1.37540     1.37460    0.021965   

       current_28  current_33  current_34  current_35  current_37  current_44  
11040    0.010940    0.000452   -0.000847   -0.000851    -0.58624     -1.4968  
11289   -0.001123   -0.000034   -0.001289   -0.001286    -0.51465     -1.4986  
35768   -0.026370    0.000478    0.019182    0.019165    -0.63484     -1.5085  
3        0.006936   -0.001277   -0.004974   -0.004966    -0.67766     -1.4963  
5599     0.012049   -0.006667    0.003245    0.003252    -0.58003     -1.4982  
...           ...         ...         ...         ...         ...         ...  
54343    0.003452   -0.011233   -0.017635   -0.017641    -0.72497     -1.4974  
38158   -0.000300    0.004420    0.000084    0.000078    -0.47078     -1.4974  
860      0.003724    0.000482   -0.002088   -0.002087    -0.54689     -1.4991  
15795   -0.026895   -0.003007    0.017799    0.017777    -0.54712     -1.5038  
56422    0.035522    0.020597   -0.015693   -0.015641    -0.70844     -1.4969  

[29254 rows x 17 columns]

In [73]:
# The shape of training dataset
print(f" The input training  data shape is {X_train.shape}")
print(f" The  output training data shape is {y_train.shape}")

 The input training  data shape is (29254, 17)
 The  output training data shape is (29254,)


In [74]:
# The shape of validation dataset
print(f" The input training  data shape is {X_valid.shape}")
print(f" The  output training data shape is {y_valid.shape}")

 The input training  data shape is (14627, 17)
 The  output training data shape is (14627,)


In [75]:
# The shape of the test dataset 
print(f" The input training  data shape is {X_valid.shape}")
print(f" The  output training data shape is {y_valid.shape}")

 The input training  data shape is (14627, 17)
 The  output training data shape is (14627,)


In [76]:
# selecting a random model 
model_rf = RandomForestClassifier()
model_rf.fit(X_train, y_train)

RandomForestClassifier()

In [77]:
# accuracy scores on the three datasets
print(f" Random model training score is {model_rf.score(X_train,y_train)}")
print(f" Random model validation data score is {model_rf.score(X_valid,y_valid)}")
print(f" Random model testing score is {model_rf.score(X_test,y_test)}")

 Random model training score is 1.0
 Random model validation data score is 0.9966500307650236
 Random model testing score is 0.9972655181843041


In [78]:
# classification report for validation dataset
y_pred_va = model_rf.predict(X_valid)
print(classification_report(y_pred_va,y_valid))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1343
           2       0.99      1.00      1.00      1336
           3       1.00      0.99      1.00      1303
           4       1.00      1.00      1.00      1303
           5       0.99      1.00      0.99      1295
           6       1.00      1.00      1.00      1335
           7       1.00      1.00      1.00      1396
           8       0.99      1.00      1.00      1331
           9       0.99      1.00      1.00      1311
          10       1.00      0.99      0.99      1316
          11       1.00      1.00      1.00      1358

    accuracy                           1.00     14627
   macro avg       1.00      1.00      1.00     14627
weighted avg       1.00      1.00      1.00     14627



### Finding the best model using Hyperparameter validation

In [81]:
# Define a grid of hyperparameters to search over
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [5, 10],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2],
}

In [82]:
# Create a Grid Search CV object and fit it to the Validation data
grid_search = GridSearchCV(model_rf, param_grid, cv=5)
grid_search.fit(X_valid, y_valid)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [5, 10], 'min_samples_leaf': [1, 2],
                         'min_samples_split': [2, 5],
                         'n_estimators': [50, 100]})

In [83]:
grid_search.best_params_

{'max_depth': 10,
 'min_samples_leaf': 2,
 'min_samples_split': 5,
 'n_estimators': 100}

In [84]:
# best classification tree for the above data
best_rf = RandomForestClassifier(max_depth = 10, min_samples_leaf= 1, min_samples_split= 5, n_estimators= 50)
best_rf.fit(X_train,y_train)
filename = 'RF_class.sav'
pickle.dump(best_rf, open(filename, 'wb'))

### Accuracy of the models

In [85]:
# Best model training 
best_rf.fit(X_train,y_train)
# Accuracy scores of best tree on different datasets
y_train_pred = best_rf.predict(X_train)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred)}")
y_valid_pred = best_rf.predict(X_valid) 
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred)}")
y_test_pred = best_rf.predict(X_test)
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred)}")      

 The training data accuracy for the best model is 0.9910097764408285
 The validation data accuracy for the best model is 0.9863266561837697
 The testing data accuracy for the best model is 0.9867377631938747


### Confusion matrices for Training data, Validation data and Testing data

In [86]:
### Training Data
print(confusion_matrix(y_train,y_train_pred))

[[2623    0    0    0    0   20    0    0    0    0    0]
 [   0 2593    0    0    0    1    0    0    8   21    0]
 [   0    0 2653    0   31    0    0    0    1    0    0]
 [   0    0   18 2655    6    0    0    0    0    0    0]
 [   0    0   21    3 2660    0    0   32    0    0    0]
 [   8    0    0    0    0 2602    0    0   16    0    0]
 [   0    0    0    0    0    0 2609    0    0    0    0]
 [   0    0    0    8   33    0    0 2624    0    0    0]
 [   8    1    0    0    1   25    0    0 2658    0    0]
 [   0    1    0    0    0    0    0    0    0 2662    0]
 [   0    0    0    0    0    0    0    0    0    0 2652]]


In [87]:
# confusion matrix for validation data
print(confusion_matrix(y_valid,y_valid_pred))

[[1333    0    0    0    0   11    0    0    1    0    0]
 [   0 1309    0    0    0    1    0    0    7   21    1]
 [   0    0 1276    0   17    0    0    0    0    0    0]
 [   0    0    8 1282    9    0    0    0    0    0    0]
 [   0    0   19    1 1263    0    0   22    0    0    0]
 [   7    0    0    0    0 1318    0    0   11    0    1]
 [   0    0    0    0    0    0 1396    0    0    0    0]
 [   0    0    0    9   25    0    0 1301    0    0    0]
 [   0    3    0    0    0   14    0    0 1293    4    0]
 [   0    6    0    0    0    1    0    0    1 1300    0]
 [   0    0    0    0    0    0    0    0    0    0 1356]]


In [88]:
# Confusion matrix for testing data
print(confusion_matrix(y_test,y_test_pred))

[[1315    0    0    0    0   12    0    0    4    0    0]
 [   0 1336    1    0    0    2    0    0    4   13    1]
 [   0    0 1315    0   26    0    0    0    0    0    0]
 [   0    0    3 1333    5    0    0    0    0    0    0]
 [   0    0   15    3 1260    0    0   20    0    0    0]
 [  14    0    0    0    0 1332    0    0   10    0    0]
 [   0    0    0    0    0    0 1314    0    0    0    0]
 [   0    1    0    8   20    0    0 1290    0    0    0]
 [   3    3    1    0    0   16    0    1 1286    2    0]
 [   0    6    0    0    0    0    0    0    0 1342    0]
 [   0    0    0    0    0    0    0    0    0    0 1311]]


### Classification Report for all the models

In [89]:
#Classification report for the training data
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      2643
           2       1.00      0.99      0.99      2623
           3       0.99      0.99      0.99      2685
           4       1.00      0.99      0.99      2679
           5       0.97      0.98      0.98      2716
           6       0.98      0.99      0.99      2626
           7       1.00      1.00      1.00      2609
           8       0.99      0.98      0.99      2665
           9       0.99      0.99      0.99      2693
          10       0.99      1.00      1.00      2663
          11       1.00      1.00      1.00      2652

    accuracy                           0.99     29254
   macro avg       0.99      0.99      0.99     29254
weighted avg       0.99      0.99      0.99     29254



In [90]:
# Classification report for the testing data
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1331
           2       0.99      0.98      0.99      1357
           3       0.99      0.98      0.98      1341
           4       0.99      0.99      0.99      1341
           5       0.96      0.97      0.97      1298
           6       0.98      0.98      0.98      1356
           7       1.00      1.00      1.00      1314
           8       0.98      0.98      0.98      1319
           9       0.99      0.98      0.98      1312
          10       0.99      1.00      0.99      1348
          11       1.00      1.00      1.00      1311

    accuracy                           0.99     14628
   macro avg       0.99      0.99      0.99     14628
weighted avg       0.99      0.99      0.99     14628



In [91]:
# classification report for the validation data
print(classification_report(y_valid,y_valid_pred))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1345
           2       0.99      0.98      0.99      1339
           3       0.98      0.99      0.98      1293
           4       0.99      0.99      0.99      1299
           5       0.96      0.97      0.96      1305
           6       0.98      0.99      0.98      1337
           7       1.00      1.00      1.00      1396
           8       0.98      0.97      0.98      1335
           9       0.98      0.98      0.98      1314
          10       0.98      0.99      0.99      1308
          11       1.00      1.00      1.00      1356

    accuracy                           0.99     14627
   macro avg       0.99      0.99      0.99     14627
weighted avg       0.99      0.99      0.99     14627



### ROC_AUC score of the models 

In [92]:
# roc auc score for training data
y_train_prob = best_rf.predict_proba(X_train)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the validation data
y_valid_prob = best_rf.predict_proba(X_valid)
print(f" The roc_auc score for the validation data is {roc_auc_score(y_valid,y_valid_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the testing data
y_test_prob = best_rf.predict_proba(X_test)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 0.9999219377376288
 The roc_auc score for the validation data is 0.9998211425220086
 The roc_auc score for the testing data is 0.9997014510862904


### Recall score of the models

In [93]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred,average= 'macro')}")
# recall score for validation data
print(f" The recall score for the validation data is {recall_score(y_valid,y_valid_pred,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test,y_test_pred,average= 'macro')}")

 The recall score for the training data is 0.9910549276431125
 The recall score for the validation data is 0.9862252402573422
 The recall score for the testing data is 0.9867200043359645


### F1 score of the models

In [94]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train,y_train_pred,average= 'weighted')}")
# F-1 score for validation data
print(f" The f-1 score for the validation data is {f1_score(y_valid,y_valid_pred,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_test,y_test_pred,average= 'weighted')}")

 The f-1 score for the training data is 0.9910148575471823
 The f-1 score for the validation data is 0.9863319830180551
 The f-1 score for the testing data is 0.9867429108628423


### Now using the best model from Part 3 with the above selected variables. Here, we got Multi Layer Perceptron (Deep Learning Model) as the best one.

In [95]:
# Importing the deep learning model
from sklearn.neural_network import MLPClassifier
# Scaling is very important in the case of linear regression
scaler = MinMaxScaler()
scaled_X = scaler.fit_transform(X)
print(scaled_X)

[[0.54585804 0.46159247 0.47343561 ... 0.37853362 0.46237036 0.72596154]
 [0.44420547 0.35720615 0.50461629 ... 0.45881715 0.48743477 0.69711538]
 [0.45973556 0.49228171 0.47242496 ... 0.50367823 0.45455661 0.62019231]
 ...
 [0.62362286 0.42903357 0.51236877 ... 0.50802255 0.96824483 0.37019231]
 [0.73932528 0.66981342 0.53213293 ... 0.49019982 0.90507422 0.39903846]
 [0.87696412 0.80365741 0.51213293 ... 0.46341956 0.90060113 0.34615385]]


In [96]:
# dividing the dataset into train,test and validation sets
X_train, X_rem, y_train, y_rem  = train_test_split(scaled_X, y, train_size = 0.5, random_state = 100)
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size = 0.5, random_state = 100)

In [97]:
# Taking MLP model
mlp = MLPClassifier()
#fitting MLP model with training data
mlp.fit(X_train,y_train)

C:\Users\Mohith Varma\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier()

In [98]:
# Finding Predictions for the MLP model
y_train_pred_mlp = mlp.predict(X_train)
y_valid_pred_mlp = mlp.predict(X_valid)
y_test_pred_mlp  = mlp.predict(X_test)

In [99]:
#Printing the accuracies for the MLP model
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred_mlp)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred_mlp)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred_mlp)}")      

 The training data accuracy for the best model is 0.9819853695221167
 The validation data accuracy for the best model is 0.9779175497367881
 The testing data accuracy for the best model is 0.9767569045665846


### Hyper Parameter Tuning for the MLP model

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
mlp = MLPClassifier()
# Define the parameter grid
param_grid = {
    'hidden_layer_sizes': [(100,), (200,), (500,), (1000,)],
    'activation': ['relu', 'logistic'],
    'solver': ['adam', 'sgd'],
    'alpha': [0.0001, 0.001, 0.01],
    'learning_rate': ['constant', 'adaptive'],
}

# Perform grid search cross-validation

clf = RandomizedSearchCV(mlp, param_grid, random_state=0)
clf.fit(X_train, y_train)

In [101]:
# Print the best hyperparameters
print(f'Best hyperparameters: {clf.best_params_}')

Best hyperparameters: {'solver': 'adam', 'learning_rate': 'adaptive', 'hidden_layer_sizes': (50,), 'alpha': 0.001, 'activation': 'relu'}


In [102]:
# best model 
best_model_mlp =  MLPClassifier(solver= 'adam', learning_rate= 'adaptive', hidden_layer_sizes= (500,), alpha= 0.001, activation= 'relu')
best_model_mlp.fit(X_train,y_train)

C:\Users\Mohith Varma\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:692: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(alpha=0.001, hidden_layer_sizes=(500,), learning_rate='adaptive')

### Accuracies for Training, Testing and Validation Datasets for the best model.

In [103]:
y_train_pred_best_mlp = best_model_mlp.predict(X_train)
y_valid_pred_best_mlp = best_model_mlp.predict(X_valid)
y_test_pred_best_mlp  = best_model_mlp.predict(X_test)
print(f" The training data accuracy for the best model is {accuracy_score(y_train,y_train_pred_best_mlp)}")
print(f" The validation data accuracy for the best model is {accuracy_score(y_valid,y_valid_pred_best_mlp)}")
print(f" The testing data accuracy for the best model is {accuracy_score(y_test,y_test_pred_best_mlp)}")      

 The training data accuracy for the best model is 0.9943255623162645
 The validation data accuracy for the best model is 0.9903602926095577
 The testing data accuracy for the best model is 0.988651900464862


### Confusion Matrices for Training, Testing and Validation Datasets for the best model.

In [104]:
### Training Data
print(confusion_matrix(y_train,y_train_pred_best_mlp))

[[2665    0    0    0    0   19    0    0    0    0    0]
 [   0 2551    0    0    0    0    0    0    1   11    0]
 [   0    0 2737    0    2    0    0    0    0    0    0]
 [   0    0    2 2686    0    0    0    0    0    0    0]
 [   0    0   19    2 2669    0    0   25    0    1    0]
 [  16    0    0    0    0 2585    0    1    6    0    0]
 [   0    0    0    0    0    0 2686    0    0    0    0]
 [   0    0    0    2   18    1    0 2634    0    1    0]
 [   3    1    0    0    0   12    0    1 2681    1    0]
 [   0   21    0    0    0    0    0    0    0 2596    0]
 [   0    0    0    0    0    0    0    0    0    0 2598]]


In [105]:
### validation Data
print(confusion_matrix(y_valid,y_valid_pred_best_mlp))

[[1320    0    0    0    0   12    0    0    0    0    0]
 [   0 1377    0    1    0    0    0    0    0   11    0]
 [   0    0 1286    0    3    0    0    0    1    0    0]
 [   0    0    0 1335    0    0    0    0    0    1    0]
 [   0    0    9    0 1280    0    0   13    0    0    0]
 [   8    0    0    0    0 1319    0    0   13    0    0]
 [   0    0    0    2    0    0 1303    0    0    0    0]
 [   1    0    0    4   16    0    0 1298    0    0    0]
 [   1    1    2    0    0    7    0    0 1314    0    0]
 [   0   35    0    0    0    0    0    0    0 1308    0]
 [   0    0    0    0    0    0    0    0    0    0 1346]]


In [106]:
### Testing Data
print(confusion_matrix(y_test,y_test_pred_best_mlp))

[[1295    0    0    0    0    7    0    0    1    0    0]
 [   0 1351    0    0    0    0    0    0    0   15    1]
 [   0    0 1285    0    4    1    0    0    0    0    0]
 [   0    0    3 1291    0    0    0    1    0    0    0]
 [   0    0    7    2 1271    0    0   21    0    0    0]
 [  12    0    1    0    0 1347    0    0   11    0    0]
 [   0    0    0    0    0    0 1328    0    0    0    0]
 [   0    0    0    1   21    0    0 1320    2    0    0]
 [   2    1    5    0    0   15    0    0 1272    0    0]
 [   0   31    0    0    0    0    0    0    1 1327    0]
 [   0    0    0    0    0    0    0    0    0    0 1375]]


### Classification Reports for Training, Testing and Validation Datasets for the best model.

In [107]:
#Classification report for the training data
print(classification_report(y_train,y_train_pred_best_mlp))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      2684
           2       0.99      1.00      0.99      2563
           3       0.99      1.00      1.00      2739
           4       1.00      1.00      1.00      2688
           5       0.99      0.98      0.99      2716
           6       0.99      0.99      0.99      2608
           7       1.00      1.00      1.00      2686
           8       0.99      0.99      0.99      2656
           9       1.00      0.99      1.00      2699
          10       0.99      0.99      0.99      2617
          11       1.00      1.00      1.00      2598

    accuracy                           0.99     29254
   macro avg       0.99      0.99      0.99     29254
weighted avg       0.99      0.99      0.99     29254



In [108]:
#Classification report for the validation data
print(classification_report(y_valid,y_valid_pred_best_mlp))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1332
           2       0.97      0.99      0.98      1389
           3       0.99      1.00      0.99      1290
           4       0.99      1.00      1.00      1336
           5       0.99      0.98      0.98      1302
           6       0.99      0.98      0.99      1340
           7       1.00      1.00      1.00      1305
           8       0.99      0.98      0.99      1319
           9       0.99      0.99      0.99      1325
          10       0.99      0.97      0.98      1343
          11       1.00      1.00      1.00      1346

    accuracy                           0.99     14627
   macro avg       0.99      0.99      0.99     14627
weighted avg       0.99      0.99      0.99     14627



In [109]:
#Classification report for the testing data
print(classification_report(y_test,y_test_pred_best_mlp))

              precision    recall  f1-score   support

           1       0.99      0.99      0.99      1303
           2       0.98      0.99      0.98      1367
           3       0.99      1.00      0.99      1290
           4       1.00      1.00      1.00      1295
           5       0.98      0.98      0.98      1301
           6       0.98      0.98      0.98      1371
           7       1.00      1.00      1.00      1328
           8       0.98      0.98      0.98      1344
           9       0.99      0.98      0.99      1295
          10       0.99      0.98      0.98      1359
          11       1.00      1.00      1.00      1375

    accuracy                           0.99     14628
   macro avg       0.99      0.99      0.99     14628
weighted avg       0.99      0.99      0.99     14628



### ROC_auc_score for the best model.

In [110]:
# roc auc score for training data
y_train_prob = best_model_mlp.predict_proba(X_train)
print(f" The roc_auc score for the training data is {roc_auc_score(y_train,y_train_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the validation data
y_valid_prob = best_model_mlp.predict_proba(X_valid)
print(f" The roc_auc score for the validation data is {roc_auc_score(y_valid,y_valid_prob,average='weighted',multi_class='ovr')}")
# roc auc score for the testing data
y_test_prob = best_model_mlp.predict_proba(X_test)
print(f" The roc_auc score for the testing data is {roc_auc_score(y_test,y_test_prob,average='weighted',multi_class='ovr')}")

 The roc_auc score for the training data is 0.999922176856319
 The roc_auc score for the validation data is 0.9998080774452239
 The roc_auc score for the testing data is 0.9998215175585333


### Recall score for the best model 

In [111]:
# recall score for training data
print(f" The recall score for the training data is {recall_score(y_train,y_train_pred_best_mlp,average= 'macro')}")
# recall score for validation data
print(f" The recall score for the validation data is {recall_score(y_valid,y_valid_pred_best_mlp,average= 'macro')}")
# recall score for test data
print(f" The recall score for the testing data is {recall_score(y_test,y_test_pred_best_mlp,average= 'macro')}")

 The recall score for the training data is 0.9943331050729739
 The recall score for the validation data is 0.9903742742889886
 The recall score for the testing data is 0.9886783587338985


### F1-score for the best model 

In [112]:
# F-1 score for training data
print(f" The f-1 score for the training data is {f1_score(y_train,y_train_pred_best_mlp,average= 'weighted')}")
# F-1 score for validation data
print(f" The f-1 score for the validation data is {f1_score(y_valid,y_valid_pred_best_mlp,average= 'weighted')}")
# F-1 score for test data
print(f" The f-1 score for the testing data is {f1_score(y_test,y_test_pred_best_mlp,average= 'weighted')}")

 The f-1 score for the training data is 0.9943231033896528
 The f-1 score for the validation data is 0.9903566464668352
 The f-1 score for the testing data is 0.9886466290187369
